version: "3"

services:
  
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - "./local_file/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
