version: "3"

services:
  
  postgres:
    image: postgres
    container_name: postgresql
    restart: always
    environment: 
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - "./local_file/postgresql/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
